# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Adidas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Adidas
  pod 'SwiftGen', '~> 6.0'

  target 'AdidasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdidasUITests' do
    # Pods for testing
  end

end
